#!/bin/bash

set +e

usage(){
  echo "Usage: builder <golang image:version> <code path> <code release tag> <main.go path> <binary name>"
  echo "e.g: builder golang:1.12.12 github.com/helm/chartmuseum v0.9.0 cmd/chartmuseum chartm"
  exit 1
}

if [ $# != 5 ]; then
  usage
fi

GOLANG_IMAGE="$1"
GIT_PATH="$2"
CODE_VERSION="$3"
MAIN_GO_PATH="$4"
BIN_NAME="$5"

set -e

echo "GOLANG_IMAGE is ${GOLANG_IMAGE}"
echo "GIT_PATH is ${GIT_PATH}"
echo "CODE_VERSION is ${CODE_VERSION}"
echo "MAIN_GO_PATH is ${MAIN_GO_PATH}"
echo "BIN_NAME is ${BIN_NAME}"


cd `dirname $0`

mkdir -p binary
rm -rf binary/$BIN_NAME || true
cp compile.sh binary/

docker run -it --rm -v $PWD/binary:/go/bin --name chartserver_builder $GOLANG_IMAGE /bin/bash /go/bin/compile.sh $GIT_PATH $CODE_VERSION $MAIN_GO_PATH $BIN_NAME
